[workspace]
authors = ["Alfredo <alfredo.hernandez@ug.uchile.cl>"]
channels = ["conda-forge"]
name = "4targets"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
sdl2 = ">=2.32.56,<3"
ffmpeg = ">=8.0.0,<9"

[pypi-dependencies]
stable-baselines3 = ">=2.7.0, <3"
numpy = ">=2.3.4, <3"
scipy = ">=1.16.3, <2"
lmfit = ">=1.3.4, <2"
gymnasium = { version = ">=1.2.1, <2", extras = ["other"] }
torch = ">=2.9.0, <3"
tensorboard = ">=2.20.0, <3"
matplotlib = ">=3.10.7, <4"
opencv-python = ">=4.11.0.86, <5"
plotly = ">=6.3.1, <7"
kaleido = ">=1.1.0, <2"
torchvision = ">=0.24.0, <0.25"
moviepy = ">=2.2.1, <3"
pygame = ">=2.6.1, <3"
ale-py = ">=0.11.2, <0.12"
autorom = ">=0.6.1, <0.7"
